version: 2
updates:
  # Enable version updates for npm packages in star-node-stack-helper
  - package-ecosystem: "npm"
    directory: "libs/star-node-stack-helper"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "juliosousa"
    assignees:
      - "juliosousa"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "star-node-stack-helper"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "@aws-sdk/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@opensearch-project/opensearch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jest"
        update-types: ["version-update:semver-major"]
    # Allow all update types for minor and patch
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
