name: Check Execution Context

on:
  workflow_dispatch:

jobs:
  check-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug repository context
        run: |
          echo "=== Repository Information ==="
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Event: ${{ github.event_name }}"
          echo ""

          echo "=== Current working directory ==="
          pwd
          echo ""

          echo "=== Root directory contents ==="
          ls -la
          echo ""

          echo "=== Checking for common directories ==="
          for dir in libs frontend microservices mobile infra; do
            if [ -d "$dir" ]; then
              echo "✅ Found directory: $dir"
              ls -la "$dir" | head -5
            else
              echo "❌ Directory not found: $dir"
            fi
          done
          echo ""

          echo "=== Looking for star-node-stack-helper ==="
          find . -name "*star-node-stack-helper*" -type d 2>/dev/null || echo "No star-node-stack-helper directories found"
          echo ""

          echo "=== Looking for package.json files ==="
          find . -name "package.json" 2>/dev/null | head -10 || echo "No package.json files found"
          echo ""

          echo "=== Looking for pnpm-lock.yaml files ==="
          find . -name "pnpm-lock.yaml" 2>/dev/null || echo "No pnpm-lock.yaml files found"
