name: Release Notification

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = context.payload;

            // Create a comment in the repository
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1, // You can change this to a specific issue number
              body: `🎉 **New Release Published!**
              
              **Version:** ${release.tag_name}
              **Name:** ${release.name}
              
              📦 **NPM Package:** https://www.npmjs.com/package/star-node-stack-helper
              📋 **Release Notes:** ${release.html_url}
              
              ${release.body ? `\n**Changes:**\n${release.body}` : ''}
              
              ---
              *This notification was automatically generated by GitHub Actions.*`
            });

            // You can also add Slack, Discord, or other notifications here
            console.log(`Release ${release.tag_name} published successfully!`);
